### ISSUE TITLE
Option to clarify cancellation dates

### ISSUE THREAD

**Issue by janrieke** [janrieke/contractmanager#13]
Add an option to clarify the final cancellation date of a contract. F.e. many contracts are cancellable only by waiting a specific period until the end of the month.

**Comment by janrieke** [comment]
Ich verstehe das Ticket nicht so ganz. Was soll hier genau klargestellt werden? Brauchen wir hier ein neues Feature bzw. ein durch eine Option veränderbares Verhalten?

**Comment by janrieke** [comment]
Ich vermute, auf Deutsch kann ich es besser beschreiben. Was ich meinte, war ein Feature, bei dem man z.B. festlegen kann "Kündigungsfrist zwei Wochen zum Monatsende" an Stelle des bisher automatisch generierten Datums.

**Comment by janrieke** [comment]
Wo wäre denn dabei der Unterschied zu einem monatlich kündbaren Vertrag, der am 1. eines Monats startet und der eine Kündigungsfrist von 2 Wochen hat?

Oder ist das genau der Punkt, das der Vertrag eben nicht zwangsläufig am 1. eines Monats startet?

**Comment by janrieke** [comment]
Genau das ist es. Z.B. hier siehe Nr. 3.2.: http://www.easybell.de/agb/agb-komplett-und-voip.html
Kündigungsdatum 03.04.2015, Kündigung zum 30.04.2015 möglich
Kündigungsdatum 20.04.2015, Kündigung erst zum 31.05.2015 möglich

**Comment by janrieke** [comment]
Umgesetzt.

**Comment by mokkin** [comment]
Super!
