### ISSUE TITLE
Shortcut "Neuen Vertrag erstellen ..." MacOS (Apfel-C)

### ISSUE THREAD

**Issue by sortega306** [janrieke/contractmanager#25]
Shortcut (Apfel-C) sollte für die Standard Kopierfunktion reserviert bleiben.

**Comment by janrieke** [comment]
Oh ja, unter Windows und Linux ist das Alt+C, das kollidiert nicht. 
Vielleicht nehme ich den Shortcut einfach raus, wird vermutlich sowieso kaum jemand nutzen.

**Comment by sortega306** [comment]
Wäre super, da das Kürzel im kompletten Jamaica Umfeld, also auch in Hibiscus anspricht. Dadurch gibt es kein Copy/Paste mehr. Habe aber gesehen, dass (Apfel-N)ew noch nicht belegt ist.  Vielleicht eine Alternative?

**Comment by janrieke** [comment]
Änderung ist jetzt mit Version 0.5.5 released. Update einfach per Jameica-Plugin-Update.
