### ISSUE TITLE
Add payment dates

### ISSUE THREAD

**Issue by janrieke** [janrieke/contractmanager#5]
Use payment dates to estimate the actual financial impact within a month (in the graphical analyses).

**Comment by DanielRiek** [comment]
+1 for being able set fixed payment dates (optional). For example quarterly payments like GEZ (15.04, 15.07, etc.) or biannual/annual payments like car insurance with a significant impact on the monthly "budget".

**Comment by janrieke** [comment]
Done here. Further improvements will follow (e.g., #18).
